# Generated by Django 3.1.6 on 2021-03-17 13:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('year', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('synopsis', models.TextField()),
                ('admitad_link', models.URLField()),
                ('poster_url', models.URLField()),
                ('ivi_rate', models.FloatField()),
                ('kp_rate', models.CharField(max_length=10)),
                ('imdb_rate', models.CharField(max_length=10)),
                ('ivi_id', models.IntegerField(unique=True)),
                ('kp_id', models.IntegerField()),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
            ],
            options={
                'db_table': 'ivi_film',
            },
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('year', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('synopsis', models.TextField()),
                ('admitad_link', models.URLField()),
                ('poster_url', models.URLField()),
                ('ivi_rate', models.FloatField()),
                ('kp_rate', models.CharField(max_length=10)),
                ('imdb_rate', models.CharField(max_length=10)),
                ('ivi_id', models.IntegerField(unique=True)),
                ('kp_id', models.IntegerField()),
                ('genres', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), size=None)),
            ],
            options={
                'db_table': 'ivi_serial',
            },
        ),
    ]
