# Generated by Django 3.1.6 on 2021-03-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imdb_links',
            field=models.URLField(max_length=220, null=True, verbose_name='ИМДБ ссылка'),
        ),
        migrations.AlterField(
            model_name='film',
            name='imdb_rate',
            field=models.FloatField(null=True, verbose_name='ИМДБ рейтинг'),
        ),
        migrations.AlterField(
            model_name='film',
            name='kp_links',
            field=models.URLField(max_length=220, null=True, verbose_name='КП ссылка'),
        ),
        migrations.AlterField(
            model_name='film',
            name='kp_rate',
            field=models.FloatField(null=True, verbose_name='КП рейтинг'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='imdb_links',
            field=models.URLField(max_length=220, null=True, verbose_name='ИМДБ ссылка'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='imdb_rate',
            field=models.FloatField(null=True, verbose_name='ИМДБ рейтинг'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='kp_links',
            field=models.URLField(max_length=220, null=True, verbose_name='КП ссылка'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='kp_rate',
            field=models.FloatField(null=True, verbose_name='КП рейтинг'),
        ),
    ]
