# Generated by Django 3.1.6 on 2021-03-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20210311_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='imdb_rate',
            field=models.CharField(max_length=50, null=True, verbose_name='ИМДБ рейтинг'),
        ),
        migrations.AlterField(
            model_name='film',
            name='kp_rate',
            field=models.CharField(max_length=50, null=True, verbose_name='КП рейтинг'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='imdb_rate',
            field=models.CharField(max_length=50, null=True, verbose_name='ИМДБ рейтинг'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='kp_rate',
            field=models.CharField(max_length=50, null=True, verbose_name='КП рейтинг'),
        ),
    ]
