# Generated by Django 3.1.6 on 2021-03-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20210317_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.CharField(max_length=220, verbose_name='Ссылка или file_id')),
                ('text', models.TextField()),
            ],
            options={
                'db_table': 'promo',
            },
        ),
    ]
