# Generated by Django 3.0.11 on 2021-01-26 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Films',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=220, verbose_name='Название')),
                ('links', models.CharField(max_length=220, verbose_name='Ссылка')),
                ('kp_rate', models.FloatField(verbose_name='КП рейтинг')),
                ('kp_links', models.CharField(max_length=220, verbose_name='КП ссылка')),
                ('imdb_rate', models.FloatField(verbose_name='ИМДБ рейтинг')),
                ('imdb_links', models.CharField(max_length=220, verbose_name='ИМДБ ссылка')),
            ],
        ),
    ]
