# Generated by Django 3.0.11 on 2021-01-26 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220, verbose_name='Логин')),
                ('user_id', models.IntegerField(verbose_name='Телеграм айди')),
            ],
        ),
    ]
