# Generated by Django 3.1.6 on 2021-03-26 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210326_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', to_field='user_id', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='Телеграм айди'),
        ),
    ]
