# Generated by Django 3.2.3 on 2021-06-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210405_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='animation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
