# Generated by Django 3.1.6 on 2021-03-11 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tosub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tosub',
            name='ch_id',
            field=models.CharField(max_length=50, verbose_name='Айди канала'),
        ),
    ]
