# Generated by Django 3.1.6 on 2021-03-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tosub', '0002_auto_20210311_0230'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tosub',
            table='tosub',
        ),
    ]
